name: record_to_talk
description: "Translate each other's conversations into text."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  record: ^5.1.2
  dio: ^5.7.0

  shared_preferences: ^2.3.2

  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  uuid: ^4.5.0
  package_info_plus: ^8.0.2
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
